pannello_amministrazione:
    resource: "@PannelloAmministrazioneBundle/Resources/config/routing.yml"
    prefix:   /

fi_core:
    resource: "@FiCoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
#HOMEPAGE ROUTE
homepage:
    path:      /
    defaults: { _controller: FiCoreBundle:Ffprincipale:index }
